name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd client
          pnpm install

      - name: Build React App
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
          VITE_EDGE_FUNCTIONS_API_KEY: ${{ secrets.VITE_EDGE_FUNCTIONS_API_KEY }}
        run: |
          cd client
          pnpm run build

  deploy:
    runs-on: self-hosted
    needs: [build]
    env:
      PROJECT_DIR: /var/www/bingo
    steps:
      - name: Copy files to /var/www/bingo
        run: |
          rm -rf $PROJECT_DIR/client/dist
          rm -rf client/node_modules
          cp -r ./ $PROJECT_DIR
